# Generated by Django 5.2.1 on 2025-05-19 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["symbol"], name="trading_sto_symbol_a737b0_idx"
                    ),
                    models.Index(fields=["name"], name="trading_sto_name_573ce6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("daily_return", models.DecimalField(decimal_places=4, max_digits=8)),
                ("total_return", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "realized_gain_loss",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "unrealized_gain_loss",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="trading.portfolio",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["portfolio", "date"],
                        name="trading_per_portfol_daa502_idx",
                    )
                ],
                "unique_together": {("portfolio", "date")},
            },
        ),
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cash_balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="trading.portfolio",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["portfolio", "timestamp"],
                        name="trading_por_portfol_96cade_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="trading.portfolio",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trading.stock"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["portfolio", "stock"],
                        name="trading_sto_portfol_6911fb_idx",
                    )
                ],
                "unique_together": {("portfolio", "stock")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trading.stock"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="trading_tra_user_id_4b74b9_idx",
                    ),
                    models.Index(
                        fields=["stock", "timestamp"],
                        name="trading_tra_stock_i_7f0f45_idx",
                    ),
                ],
            },
        ),
    ]
